### ISSUE TITLE
SendRoutingInfo	

### ISSUE THREAD

**Issue by Bugurr** [SigPloiter/SigPloit#10]
What do we write in MSC GT?

And how do we find MSC GT?

**Comment by nhanth87** [comment]
Hi,
SRI is sent to HLR not MSC, so the GT address and SSN, PC should be HLR

SRI response will contain MSC/VLR info

Br,
TN

**Comment by Bugurr** [comment]
how can we make PC HLR for testing?

**Comment by SigPloiter** [comment]
@nhanth87 yes you are correct, i wrote the source node instead of the destination, my bad, its corrected now

**Comment by SigPloiter** [comment]
@Bugurr the MSC GT is up to you if you are testing in a virtual lab it could be a number like in its internaitonal format (i.e +4412345678979). But in real life scenario, your SS7 provider will provide you the GT and other parameters that you could use.

As for the PC HLR for testing, the values for testing are available under each server side message in the "Testing" directory

**Comment by Bugurr** [comment]
SigPloiter 

Thank you for the help.

what is required for the virtual lab for the SigPloit to work?


[*]Locating Target: 201124683579
[*]Location Retrieval for Target 201124683579 is processing..

[-]Error: onInvokeTimeout for Dialog=1 and invokeId=0[-]Error: onDialogTimeout for DialogId=1

with your values I m getting the above error.

**Comment by SigPloiter** [comment]
@Bugurr can you please provide me the values you put from the client side

and do you execute the server side jar file ? like this: java -jar SendRoutingInfo.jar on a different virtual machine ? and assigned the IP 192.168.58.102 ?

**Comment by Bugurr** [comment]
@SigPloiter ohh u mean i have to run sigploit on diferrent machine and sendroutinginfo.jar on a different mahcine??? and where i have to put IP of  sendroutinginfo.jar machine in client or peer??

**Comment by SigPloiter** [comment]
@Bugurr yes exactly

on VM 1:
------------
-network IP: 192.168.58.101
-run SigPloit and use the values provided under the "Testing" Directory

on VM 2:
-----------
- network IP: 192.168.58.102
-run the below
   java -jar Testing/Server/Attacks/Location_Tracking/SendRoutingInfo_Server/SendRoutingInfo.jar

hope this is clear :)

**Comment by Bugurr** [comment]
@SigPloiter  yup got it thanks sorry but 1 more thing that in real life environment what will be the scenario of client PC and Peer PC and SendRoutingInfo.jar. Thanks

**Comment by Bugurr** [comment]
@SigPloiter on peer PC m running jar file getting this error (No such File Found MapLoadServerSccpStack_Management2.xml )all files generated but this file not generated.. Thanks

**Comment by Bugurr** [comment]
@SigPloiter MapLoadServerSccpStack_Management2.xml error resolved sorry plzz tell the real life scenario...

**Comment by SigPloiter** [comment]
@Bugurr in real life scenario when you get an access from SS7 provider they will provide the below:

1- The global title you will use (GT)
2- The point code (client PC) that you will used, normally in real life scenarios its 4-5 digits
3- Their point code , so you can send the SS7 packets through them
4- Their IP address that you will have SCTP association with

each SS7 packet used has its corresponding node in the telecom operator that is responsible for the response. In case of SendRoutingInfo if its allowed from the operator side, after some routing and internal lookups the HLR that has the subscriber's profile will response, the HLR of susbcriber is identified by the MSISDN(phone number) that you provide
