### ISSUE TITLE
Project files clean up

### ISSUE THREAD

**Issue by alexmozzhakov** [SigPloiter/SigPloit#103]
If no installation is required, you can then move SiGploit.py to the root folder, rename bin to something like modules, add __init__.py to the folder and use 
`import modules.tracking` inside SiGploit.py
This will make running of the project more clear

**Comment by SigPloiter** [comment]
@alexmozzhakov thanks so much for your contribution your pull request is merged. I will work on your suggestion thanks

**Comment by alexmozzhakov** [comment]
No problem. You can assign me to this task, I will do it in about an hour.
