### ISSUE TITLE
Hello Mr loay

### ISSUE THREAD

**Issue by semo1984** [SigPloiter/SigPloit#105]
I want to contact with you about this project, i'm arabic and i wand to speak with you.
How can i contact with you.
Thank u

**Comment by kerberos27** [comment]
my email is kerberosjoo27@gmail.com

**Comment by semo1984** [comment]
But you not Mr. Loay :) 
Thank u

**Comment by kerberos27** [comment]
oh my bad i just got an email from you .... so i replied lol :)
