### ISSUE TITLE
Sctp ManagementImpl Error

### ISSUE THREAD

**Issue by InnovaHacker** [SigPloiter/SigPloit#107]
Sigploit is running fine, but i'm occuring a problem in my pc(windows 8)
log4j:WARN No appenders could be found for logger <org.mobicents.protocols.sctp.ManagementImpl>.
log4j:WARN Please initialize the log4j system properly.

**Comment by humptysharma123** [comment]
1. SCTP protocol is not supported on windows machine by default try it on Linux/Unix machines for eg Ubuntu or Kali.
2. The message you posted above is not an error it is a warning for logger so ignore it.

**Comment by SigPloiter** [comment]
thanks @humptysharma123 

@InnovaHacker hope this clarifies things
