### ISSUE TITLE
[-]Error: onInvokeTimeout for Dialog=1 and invokeId=0[-]Error: onDialogTimeout f or DialogId=1

### ISSUE THREAD

**Issue by InnovaHacker** [SigPloiter/SigPloit#109]
C:\Users\Parth\Desktop\sigploit16\ATI>java -jar anytimeintorrogation.jar
Error: Unable to access jarfile anytimeintorrogation.jar

C:\Users\Parth\Desktop\sigploit16\ATI>java -jar anytimeinterrogation.jar
*********************************************
***             Locating Target           ***
*********************************************
?[34m[*]?[0mSet Client PC: 1
?[34m[*]?[0mSet Peer PC: 2
?[34m[*]?[0mSet Client IP: 42.106.93.250
?[34m[*]?[0mSet Client Port: 80
?[34m[*]?[0mSet Peer IP: 141.0.11.253
?[34m[*]?[0mSet Peer Port: 80
***Bypass some filters, try setting it to National***
?[34m[*]?[0mSet Network Indicator [0] International [1] National: 1
?[34m[*]?[0mSet Target's MSISDN: 9662221613
?[34m[*]?[0mSet your GT: 91
?[34m[*]?[0mStack components are set...
?[34m[*]?[0mInitializing the Stack...
?[34m[*]?[0mInitializing SCTP Stack ....
log4j:WARN No appenders could be found for logger (org.mobicents.protocols.sctp.
ManagementImpl).
log4j:WARN Please initialize the log4j system properly.
?[32m[+]?[0mInitialized SCTP Stack ....
?[34m[*]?[0mInitializing M3UA Stack ....
?[32m[+]?[0mInitialized M3UA Stack ....
?[34m[*]?[0mInitializing SCCP Stack ....
?[32m[+]?[0mInitialized SCCP Stack ....
?[34m[*]?[0mInitializing TCAP Stack ....
?[32m[+]?[0mInitialized TCAP Stack ....
?[34m[*]?[0mInitializing MAAP Stack ....
?[32m[+]?[0mInitialized MAP Stack ....
?[34m[*]?[0mLocating Target: 9662221613
?[34m[*]?[0mLocation Retrieval for Target 9662221613 is processing..

[-]Error: onInvokeTimeout for Dialog=1 and invokeId=0[-]Error: onDialogTimeout f
or DialogId=1

What is the meaning of this?????

**Comment by SigPloiter** [comment]
First why are you running it on windows , the sctp stack is supported on
Linux

Second this is a server side code, thus all parameters are hardcoded once
again during simulating please follow the parameters provided for each
scenario, it won't work because the pc and ip provided are wrong

**Comment by InnovaHacker** [comment]
Ok dude, i will try it on linux. Did you mean that i have to enter the same
values which are given in parameter files??

Like, sendimsi.jar's hardcoded values are
Client pc: 1
Peer pc: 2
Client ip: 192.168.56.101
Client port: 2905
Peer ip: 192.168.56.101
Peer port: 2906
Target MSISDN: ************(any of my choice)
Target HLR: ****00000000
Your GT: (any of my choice)
So i have to enter these same values, right???
And do you have any suggestion for how to use sctp on windows???
