### ISSUE TITLE
Sctp ManagementImpl Error-Kali Linux

### ISSUE THREAD

**Issue by InnovaHacker** [SigPloiter/SigPloit#110]
I tried to start sigploit on kali linux & the sctp error is still showing...
root@InnovaHacker:~/Desktop/SigPloit/SS7/Tracking/ATI# java -jar AnyTimeInterrogation.jar
*********************************************
***             Locating Target           ***
*********************************************
[*]Set Client PC: 1   
[*]Set Peer PC: 2
[*]Set Client IP: 192.168.56.101
[*]Set Client Port: 2905
[*]Set Peer IP: 192.168.56.102
[*]Set Peer Port: 2906
***Bypass some filters, try setting it to National***
[*]Set Network Indicator [0] International [1] National: 1
[*]Set Target's MSISDN: 917487989854
[*]Set your GT: 919898
[*]Stack components are set...
[*]Initializing the Stack...
[*]Initializing SCTP Stack ....
log4j:WARN No appenders could be found for logger (org.mobicents.protocols.sctp.ManagementImpl).
log4j:WARN Please initialize the log4j system properly.
[+]Initialized SCTP Stack ....
[*]Initializing M3UA Stack ....
[+]Initialized M3UA Stack ....
[*]Initializing SCCP Stack ....
[+]Initialized SCCP Stack ....
[*]Initializing TCAP Stack ....
[+]Initialized TCAP Stack ....
[*]Initializing MAAP Stack ....
[+]Initialized MAP Stack ....
[*]Locating Target: 917487989854
[*]Location Retrieval for Target 917487989854 is processing..

[-]Error: onInvokeTimeout for Dialog=1 and invokeId=0
[-]Error: onDialogTimeout for DialogId=1

**Comment by SigPloiter** [comment]
are you running the server side code ?

**Comment by InnovaHacker** [comment]
Yes...

**Comment by SigPloiter** [comment]
Please check that there is no hardcoded value for the msisdn in the
parameters

**Comment by InnovaHacker** [comment]
What???

**Comment by InnovaHacker** [comment]
And what if i want test it on live mode. Can you tell me the parameters for that??

**Comment by SigPloiter** [comment]
The msisdn parameter I Believe it's hardcoded as well check it

As for the live mode the parameters is provided to you be the SS7 provider

**Comment by InnovaHacker** [comment]
Even if when i entered right parameters, this following error is still on linux..:
[]Initializing SCTP Stack ....
log4j:WARN No appenders could be found for logger (org.mobicents.protocols.sctp.ManagementImpl).
log4j:WARN Please initialize the log4j system properly.

I don't know what to do now...

**Comment by SigPloiter** [comment]
This is not an error it says a warning, things should be working , and it's
related only to the logging not the stack

**Comment by InnovaHacker** [comment]
So, Can you tell me that how to log the sctp stack on linux???

**Comment by SigPloiter** [comment]
It's not related to sctp it's just normal logging and it work so fine it's
just a warning not an error what is the issue now ?

**Comment by InnovaHacker** [comment]
Well that's okay, but why it always shows ("
[]Location Retrieval for Target 201124683579 is processing..

[-]Error: onInvokeTimeout for Dialog=1 and invokeId=0
[-]Error: onDialogTimeout for DialogId=1     ") at last output?

**Comment by SigPloiter** [comment]
I will try to reproduce this error and tell u

**Comment by InnovaHacker** [comment]
OK, sir....

**Comment by InnovaHacker** [comment]
I just resolved this error, it was my bad....
I have one more question that what if the provider denies my connection on ss7 network so can i bypass that Request filter on provider's ss7 network????

**Comment by InnovaHacker** [comment]
On Live mode...

**Comment by naymintun800** [comment]
How did you solved that Warn thing?

**Comment by smit-agravat** [comment]
Error: onInvokeTimeout for Dialog=1 and invokeId=0  i get this how to solve it what is this ???

**Comment by SigPloiter** [comment]
That means the server on the other hand is not responding

Is this on simulation mode ? If it’s not real environment than there is a
server side you need to run

**Comment by attractor1** [comment]
I welcome you dear friends.  I need your help.  I am a beginner and apparently that NK understood that.  help me figure out what is wrong with sigploit.  who should i contact?  I will be very grateful to you.  thank you in advance to all who respond.  Regards attractor1.  my mail attrctorkz@gmail.com

**Comment by SigPloiter** [comment]
What is your issue with sogploit
Open an issue and I shall check what’s the issue

**Comment by smit-agravat** [comment]
i understand that but how can i run server side that u say sry i m mechanical guy i dont know much abt all this i m trying to learning.....

**Comment by SigPloiter** [comment]
Sigploit only works on Linux for now there shall be a docker version
shortly

**Comment by smit-agravat** [comment]
i am using kali on android

**Comment by SigPloiter** [comment]
What’s the reason for using android , you need a Linux machine

**Comment by attractor1** [comment]
Greetings.  Thanks for not giving up.  Thank God, I figured out the
installation.  Now I’ve come to a standstill.  Can tell me how can I find
out the ip client and server, as well as the client and server port by
mobile number.?  To attack ss7 and intercept sms?  Maybe there is a utility
for linux?  Grateful in advance and if you do not mind today could give an
answer.  Thank.

Ср, 30 жовт. 2019, 14:11 користувач Loay Abdelrazek <
notifications@github.com> пише:

**Comment by SigPloiter** [comment]
These are parameters you need to get from the operator you will connect to

I would suggest to read more about SS7 and how it works

**Comment by attractor1** [comment]
Hey.  Tell me, then I'm confused.  After starting SigPloit whose data must be entered.  to run live Chii need to enter ip and port address and ip and server port, to attack the mobile number?  Thank

**Comment by zeroplus4** [comment]
**how will i get access to those parameters. and who is incharger of the parameters commection...network providers or what???**

**Comment by attractor1** [comment]
Hey.  my mail is laniakeyakz@gmail.com.  Describe by e-mail what kind of
data do you need to check which particular vulnerability for penetration?
Only then is it possible to answer your question.  Thanks.

Пн, 23 груд. 2019, 10:42 користувач zeroplus4 <notifications@github.com>
пише:

**Comment by zeroplus4** [comment]
which client side will i edit for the parameters. 
client_config 
hrl
vlr
or i should edit all java jar orange marked arean 
because alot is to be edit to fix the parameters connection

**Comment by JamesSmi-ux** [comment]
Hi! I need some help. I have an rtl-sdr(Nooelec NESDR SMArt XTR Bundle - Premium RTL-SDR w/ Extended Tuning Range, Aluminum Enclosure, 0.5PPM TCXO, SMA Input & 3 Antennas) and I want to intercept sms. I have installed tools for ss7, and I'm struggling with..because I dont know how to practice..I saw a lot of versions but I dont know where to start. Can anyone help me? I will be grateful for that. Thank you

**Comment by SigPloiter** [comment]
the parameter connections is provided by whoever will provide you the
Sigtran/SS7 interconnection. Other than that the provided parameters in
this case is only for simulation environment, in real life scenarios you
get those from the provider

**Comment by JamesSmi-ux** [comment]
Thank you so much for reply. The access to the ss7 network must be bought from a provider? There is no other way?

**Comment by attractor1** [comment]
write to mail laniakeyakz@gmail.com. there are options

чт, 16 лип. 2020, 18:46 користувач JamesSmi-ux <notifications@github.com>
пише:

**Comment by JamesSmi-ux** [comment]
@attractor1 Thank you!!!!

**Comment by smit-agravat** [comment]
> I just resolved this error, it was my bad....
> I have one more question that what if the provider denies my connection on ss7 network so can i bypass that Request filter on provider's ss7 network????

hi bro how you solved that thing i am having same error

**Comment by SigPloiter** [comment]
Please use this forum only to report issues , I will not reply to any
questions regarding malicious activity

**Comment by smit-agravat** [comment]
Error: onInvokeTimeout for Dialog=1 how to solve this ? In a simple way.....

**Comment by SigPloiter** [comment]
You are connecting to an invalid IP as a destination probably
So if this is a live network it’s not accepting your connections or the IP
is wrong

**Comment by smit-agravat** [comment]
Ok thank you which ip should i enter and the client port is also confusing i am entering my pc ip as client ip but i dont understand which port should i enter????

**Comment by SigPloiter** [comment]
If you have a SS7 provider, they shall provide the port to be used

**Comment by smit-agravat** [comment]
I dont have ss7 provider....

**Comment by khurana9812** [comment]
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/root/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/root/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/root/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/root/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/root/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/root/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj





python sigploit.py not working

**Comment by kaliss7s** [comment]
same errore python sigploit.py not working
