### ISSUE TITLE
How use it? it is need device for working?

### ISSUE THREAD

**Issue by zerod4y** [SigPloiter/SigPloit#112]
Hello
i will use it for pentest telecom network
it is need device look like sdr usrp or ismi catcher?!
it is good and complete tools for telecom penetraion testing?!

**Comment by SigPloiter** [comment]
This part of telecom pentest where you are testing interconnects and
signaling doesn't need any equipment or hardware( I suggest you dive deeper
first before the pentest) if you need any help with the pentest am
available
