### ISSUE TITLE
What is Client PC and where to find...?

### ISSUE THREAD

**Issue by sathya8561** [SigPloiter/SigPloit#115]
what clent PC and port how to find ?

**Comment by SigPloiter** [comment]
sorry for my late reply, point code or (PC) is assigned to you by the operator or SS7 provider that you are connected to, its a 5 digits number

**Comment by zuhan1990** [comment]
hey! 
5 digit number!!
you mean like some operator clients have 5 digit number to activate postpaid sim card when someone purchase a new one?

**Comment by SigPloiter** [comment]
NO @zuhan1990 , its a dedicated 5 digit number for telecom communication for internal use in core network and between roaming partners

**Comment by sathya8561** [comment]
what is peer ip how to find?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by SigPloiter** [comment]
its from the sigtran/ss7 provider as well

from an ss7 provider you should get all the below parameters

peer ip
peer port
peer point code
client point code
global title
