### ISSUE TITLE
How to install please

### ISSUE THREAD

**Issue by Mouja0412** [SigPloiter/SigPloit#116]
Hi, How to install please? I tried ./installer.sh but it's not working

Thank you

**Comment by SigPloiter** [comment]
installer.sh was removed as its not needed, currently you need first to check that you have the below
java version 1.7 or +
libsctp-dev
libsctp1

then simply 
cd bin 
python SiGploit.py

**Comment by Mouja0412** [comment]
Thank you for your support. I will check that out and will keep you posted.

**Comment by Mouja0412** [comment]
Hi, 
Thank you it's working :)

**Comment by hoalan1984** [comment]
hello...i'm trying to install sigpoit, but it's not scuccess. It's allway appear 
![screenshot from 2018-07-04 09-44-34](https://user-images.githubusercontent.com/11917204/42354083-8fdc4c3e-80ee-11e8-9703-6b0deafbc1ba.png); Any success install, please help me....

**Comment by hoalan1984** [comment]
Mouja0412, can i have your email please. thanks you

**Comment by Mouja0412** [comment]
hoalan1984 : Hi, did you try this : 
currently you need first to check that you have the below
java version 1.7 or +
libsctp-dev
libsctp1

then simply
cd bin
python SiGploit.py

I don't have kali anymore, im using Mac now, so i won't be able to test the commands.

**Comment by hoalan1984** [comment]
Mouja0412, Special thank for answer....On desktop it show "No modul name attack.info "...I try to search that file in Sigploit package, but it Hasn't got that file...I thinks the SigPloit package on Gibhub is change or update by author, it's the same when you install. 
![screenshot from 2018-07-06 14-54-46](https://user-images.githubusercontent.com/11917204/42366878-8e3bc092-812c-11e8-982d-c87d5908bb6d.png)
Don't have bin folder...
if you still the SigPloit package on your driver. Please share for me....
Again, Thanks you Mouja0412 alot...Thanks you

**Comment by Mouja0412** [comment]
hoalan1984 : You are welcome. Please mention the author and check with him if the package has been updated or not. I'm sorry I don't have the package anymore, I removed Kali and I installed Mac as my primary system. Sorry again.

**Comment by hoalan1984** [comment]
Thanks friend...i mentioned with the author. But still to wait now...
ohh What's a pity...you know, i've spend much time on this tool, but up to know i can't setup it success..
Many time to thank you. Mouja0412...

**Comment by Mouja0412** [comment]
Sure the author is not available right now, hope he'll answer soon. Sure there's a fix.
Welcome and have a nice day :)

**Comment by hoalan1984** [comment]
Thanks you. Best wish for you...friend

**Comment by SigPloiter** [comment]
Hey I told u am working on this issue I will get back to you today

**Comment by hoalan1984** [comment]
Thank you SigPloit!...

**Comment by reecheekeeyz** [comment]
Still can't install ...anyone got any lucks still ?

**Comment by zeroplus4** [comment]
Chat me on whatsapp for assistance
+12028885222

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zeroplus4** [comment]
Chat me on whatsapp for quick conversation on how you can installed it, +12028885222

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Virendra136** [comment]
> Mouja0412, can i have your email please. thanks you

please gave me solution
