### ISSUE TITLE
PRI is enough ?

### ISSUE THREAD

**Issue by EhsanArio** [SigPloiter/SigPloit#117]
Hi
I get access to an E1 with PRI link.
So no PC details available.
How can i use it with SigPloit ?

**Comment by SigPloiter** [comment]
Hello , sorry for my late reply, unfortunately sigploit is compiled to be
used for sigtran, and the stack used supports dialogic hardware drivers for
E1

**Comment by SigPloiter** [comment]
BUT If u can give me more info about ur setup and ll try to help

**Comment by EhsanArio** [comment]
Thanks for your answer.

My main question is How can i access to ss7 network to test Sigploit ?
But i asked my local telecommunication center to give me an E1 link with access to SS7. But they told me SS7 is only for interconnection between telecommunication centers and not for end-users.
And they told Can give me an E1 link with access to PRI which is something like SS7 and for end-users. unfortunately in PRI no PC IP and PORT available. 

And also a SIP Trunk is available to use.

How can i access to SS7 network to test Sigploit in Live mode ?

Thanks

**Comment by SigPloiter** [comment]
there are providers that can provide SS7 interconnection for
end-users/companies but mostly they are in europe and USA, there are also
SMS service providers whom can provide you with SS7 interconnection, you
need to look for them

**Comment by EhsanArio** [comment]
Thanks for quick answer
Europe is good for me.
I tried some SIP Trunk Providers. 
Is there enough to set their server ip insteade of PC IP ?

> there are providers that can provide SS7 interconnection for
end-users/companies but mostly they are in europe and USA, there are also
SMS service providers whom can provide you with SS7 interconnection

May you please  introduce some of them and websites ?
And tell me which data do i need to get from these companies ?(PC IP and Port)

**Comment by devcoinfet** [comment]
Ok,  Here's my question.  If I were to use sip / ISUP is there a configuration in the end user part of the sip system to set all the necessary info like the point code global titles is all this still needed?

or is the setup for Your tool going to be different than if we were to use an ss7 interconnect and anyone needing said access can contact me for further details.  ss7 is the easy part i'm curious on the sip setup

**Comment by SigPloiter** [comment]
Send me ur email please to discuss more

**Comment by devcoinfet** [comment]
wabefet@gmail.com

**Comment by Adewale121** [comment]
hello bro please can you help me?i have network provider who are willing to give me any necessary parameters or Datas needed to go on live mode on sigploit but my major conncern bro , what are the parameters or datas need to be on live mode mostly for sms interception or sniffing 
thank you

**Comment by SigPloiter** [comment]
If the provider willing to give you the parameters then they know what
should they provide , did they tell you what will they provide ? If not how
did you know they are willing to provide connection ?

**Comment by Adewale121** [comment]
No actually bro.... He asked me what I really want because the way providers work in Africa I think it's different  but here is what I temporarily give







1. The global title you will use

2. The point code you will use (client PC)

3. The peer point code of the provider (Peer PC)

4. The IP address of the providers peer for SCTP associations and 

5. the used port (Peer IP, Peer port)

**Comment by SigPloiter** [comment]
Send me ur email

**Comment by xiaoxie1979** [comment]
Hi bro I have been looking for a long time, still have not found the SS7 interconnection method, maybe I can not understand the English, I have asked some VOIP providers, but they do not directly provide SS7 interconnection, I am going to find sip trunk and SMS provider Maybe I can get some data by grabbing the package. I only need the STP address and port. I have opc and dpc and globaltitle. These are the data of others. I don't know if it works for me?

**Comment by DaleMitchell** [comment]
@SigPloiter please email dalem50@gmail.com

**Comment by vportal** [comment]
Hello,

I have also been asking to a lot of SMS and VOIP providers and they don't provide SS7 access to end users. Another concern i have is if these providers that give SS7 access apply filtering rules to block certain types of SS7 messages.

Best regards.

**Comment by SigPloiter** [comment]
Yes they can filter some messages of course
