### ISSUE TITLE
libsctp.so: undefined symbol: sctp_getladdrs

### ISSUE THREAD

**Issue by userl0ser** [SigPloiter/SigPloit#120]
I'm getting:

java.lang.UnsupportedOperationException: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libsctp.so: undefined symbol: sctp_getladdrs

While trying to run the demo server for ATI

Any ideas?

EDIT: problem might be with JDK? as sctp_status for example, manages to create a sctp server...

**Comment by userl0ser** [comment]
scrap that, my bad. excellent stuff by the way 👍

**Comment by SigPloiter** [comment]
Thanks , much appreciated :)

**Comment by SigPloiter** [comment]
@userl0ser yes, what is your account ?

**Comment by userl0ser** [comment]
I've added you - dk, if that rings a bell

**Comment by SigPloiter** [comment]
i have accepted your invitation, you reached the right account
