### ISSUE TITLE
Failed to load the SCTP configuration file. 

### ISSUE THREAD

**Issue by Honik** [SigPloiter/SigPloit#122]
Hi..
when I run java -jar anyjarfile.jar I have this warn.

`root@kali:~/Scrivania/SigPloit/Testing/Server/Attacks/Location_Tracking/SendRoutingInfo_Server# java -jar SendRoutingInfo.jar 
*********************************************
***      Subscriber Information - HLR     ***
*********************************************
Input Stream = sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@c2e1f26
0    [main] DEBUG SendRoutingInfoResp  - Initializing SCTP Stack ....
489  [main] WARN  org.mobicents.protocols.sctp.ManagementImpl  - Failed to load the SCTP configuration file. 
/root/Scrivania/SigPloit/Testing/Server/Attacks/Location_Tracking/SendRoutingInfo_Server/Server_sctp.xml (File o directory non esistente)
java.net.BindException: Impossibile assegnare l'indirizzo richiesto
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.sctp.SctpServerChannelImpl.bind(SctpServerChannelImpl.java:118)
	at com.sun.nio.sctp.SctpServerChannel.bind(SctpServerChannel.java:185)
	at org.mobicents.protocols.sctp.ServerImpl.doInitSocketSctp(ServerImpl.java:183)
	at org.mobicents.protocols.sctp.ServerImpl.initSocket(ServerImpl.java:157)
	at org.mobicents.protocols.sctp.ServerImpl.start(ServerImpl.java:112)
	at org.mobicents.protocols.sctp.ManagementImpl.startServer(ManagementImpl.java:647)
	at SendRoutingInfoResp.initSCTP(SendRoutingInfoResp.java:120)
	at SendRoutingInfoResp.initializeStack(SendRoutingInfoResp.java:88)
	at SendRoutingInfoResp.main(SendRoutingInfoResp.java:388)
`

what is the problem?? The xml file is on the correct path

**Comment by SigPloiter** [comment]
Check that ur machine that acts as a server has the same IP that is set in
the parameters file “192.168.56.102”

**Comment by Honik** [comment]
Yes now the IP on the machine when I run the command is 192.168.56.102 but I have the error below. (I'm on Kali)

`*********************************************
***              SMS Spoofing             ***
*********************************************
Input Stream = sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@6aa8ceb6
0    [main] WARN  org.mobicents.protocols.ss7.sccp.impl.SccpStackImpl-MapLoadServerSccpStack  - Failed to load the Sccp Management configuration file. 
/root/Scrivania/SigPloit/Testing/Server/Attacks/Fraud/MTForwardSMS_Server/MapLoadServerSccpStack_management2.xml (File o directory non esistente)
[*]Initializing TCAP Stack ....
251  [main] WARN  org.mobicents.protocols.ss7.tcap.TCAPStackImpl-tcap  - Failed to load the TCAP Management configuration file. 
/root/Scrivania/SigPloit/Testing/Server/Attacks/Fraud/MTForwardSMS_Server/tcap_management.xml (File o directory non esistente)
[+]Initialized TCAP Stack ....
[*]Initializing MAP Stack ....
[+]Initialized MAP Stack ....

`

**Comment by SigPloiter** [comment]
No don’t worry it’s not an error, as long as it’s initakizing the stack
then no problem

**Comment by Honik** [comment]
Thank you!!
Is it possible to have a complete guide? Because I'd like to understand this one, but I don't know ho to test it. Once I've started the server (testing server) what can I do ? sigploit.py ask me code that I don't have.
Thank you for your patience

**Comment by SigPloiter** [comment]
Sure ll try to prepare a video and send it to u

**Comment by Honik** [comment]
Thank you so much. Do you need my email address

**Comment by SigPloiter** [comment]
Yes please

**Comment by Honik** [comment]
text me on rgermes@hotmail.com.
Thanks

**Comment by ch0sys** [comment]
Hello ,
SigPloiter can you help me, i have this problem . 
my email is (emil.obry@gmail.com)
