### ISSUE TITLE
having problems using the script

### ISSUE THREAD

**Issue by Abasifreke01** [SigPloiter/SigPloit#132]
hello, can you please give a tutorial on using the script to intercept sms?
i have not found any tutorial so far on using sigploit, and i need help

**Comment by SigPloiter** [comment]
You are right unfortunately there isn’t , but need to read a bit more on
how SS7 works , the interception scneario is a bit complex and needs
understanding of the underlying technology

**Comment by Abasifreke01** [comment]
so, is there no way you can help me in passing valid parameters?
or providing a documentation on how to make use of the software

**Comment by SigPloiter** [comment]
Please tell me what is the exact issue , I will send u the details on how
to work it out

But are u running it on live network or will run in a virtual lab ?

**Comment by Abasifreke01** [comment]
am running on live network

**Comment by SigPloiter** [comment]
Ok please send me ur email

**Comment by Abasifreke01** [comment]
abasifrekeeyo1@gmail.com

**Comment by Abasifreke01** [comment]
That is my email address, will really appreciate it if you can give me a guide on how to use the tool, thanks.

**Comment by SigPloiter** [comment]
Will reply to your email shortly

**Comment by asmshakib** [comment]
hello. help me please . its very hard to understand. my email is : anny_47@protonmail.com

**Comment by anny47** [comment]
hello. help me please . its very hard to understand. my email is : anny_47@protonmail.com

**Comment by khaliqbaloch** [comment]
Hi sigploiter

**Comment by khaliqbaloch** [comment]
Hello sir I need your help my email is bkhaliq53@gmail.com
