### ISSUE TITLE
Issue with SRISM with SMS home routing detection

### ISSUE THREAD

**Issue by akibsayyed** [SigPloiter/SigPloit#135]
Hi @SigPloiter 
I tried to run tool on some of operator network operator. I found something interesting which is as follows
most of time operator will give same Fake IMSI for certain amount of time, or till FWD SM or MT SM is not sent. So you should add code for MT SM after receiving SRI SM Resp. or add interval for same.

About adding interval it is not clear how much time operator will define as timeout for assigned FAKE IMSI. so better to stick with FWD SM or MT SM

**Comment by SigPloiter** [comment]
Hello @akibsayyed thanks for such great info. But i guess the issue will remain if i sent a MT SM i will not have the IMSI yet. I mean it will not be verified if its the true one or not. i agree this will be  a great issue.
But did you notice how much time is it applied as an interval at the operator?
Was the tool effective enough ? any issues ?any good results?

**Comment by akibsayyed** [comment]
Try this send srism and mt 3 times and then decide if IMSI is changing if
it is then home routing is enabled else u have correct imsi

**Comment by SigPloiter** [comment]
@akibsayyed perfect thanks , i will try it out

**Comment by TIYYA** [comment]
root@kali:~/SigPloit# python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/root/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/root/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/root/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/root/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
ImportError: No module named attacks.info

**Comment by SigPloiter** [comment]
@hoalan1984 @TIYYA issue fixed now, and please create your own threats of issues dont send on other irrelevant issues, I assume its not your first time to use github

**Comment by hoalan1984** [comment]
Thanks you @SigPloiter. i'm sorry if i've done any no good for you on github. Next time i will create my own threat NOT irrelevant issues...I'll re-download your package and reinstall it, and hope in this time i success with your fix....if i can do any think that good for you on gitbub, please tell me...one again,  thanks you so much to you.

**Comment by Olloyor7** [comment]
python sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/home/z/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/home/z/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/home/z/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/home/z/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/home/z/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/home/z/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 40, in <module>
    from gtp_v2_core.tunnel_mgmt_messages.create_bearer import CreateBearerRequest, CreateBearerResponse
  File "/home/z/SigPloit/gtp/gtp_v2_core/tunnel_mgmt_messages/create_bearer.py", line 34, in <module>
    from gtp_v2_core.commons.gtp_v2_msg_base import GTPV2MessageBase
  File "/home/z/SigPloit/gtp/gtp_v2_core/commons/gtp_v2_msg_base.py", line 36, in <module>
    from gtp_v2_information_element_base import *
  File "/home/z/SigPloit/gtp/gtp_v2_core/commons/gtp_v2_information_element_base.py", line 9, in <module>
    from IPy import IP
ImportError: No module named IPy

**Comment by SigPloiter** [comment]
Please as instructed in the installation section in the READMe run “pip
install -r requirements.txt”

**Comment by hoalan1984** [comment]
you must run: sudo apt-get install python-ipy       before run sigploit

**Comment by guyhhu** [comment]
![screenshot from 2018-08-04 21-05-44](https://user-images.githubusercontent.com/42042093/43682619-ea3a4a30-982e-11e8-8e43-de18f5e992d8.png)



I was install python 3+,pip 3 and 
pyfiglet==0.7.5
termcolor==1.1.0
colorama==0.3.9
But still I face This Problem.........Please A proper solution.......

**Comment by guyhhu** [comment]
![screenshot from 2018-08-04 21-05-44](https://user-images.githubusercontent.com/42042093/43682623-15206540-982f-11e8-871c-49b7d3ba28ca.png)
![screenshot from 2018-08-04 21-05-44](https://user-images.githubusercontent.com/42042093/43682540-9b0cce12-982c-11e8-8c9e-849960605c61.png)
I was install python 3+,pip 3 and 
pyfiglet==0.7.5
termcolor==1.1.0
colorama==0.3.9
But still I face This Problem.........Please A proper solution.......

**Comment by SigPloiter** [comment]
Please open an issue in the GTScan repo

**Comment by manjitsaha** [comment]
does this also require rtl-sdr

**Comment by hoalan1984** [comment]
No, i does not require

**Comment by manjitsaha** [comment]
then how this tool capture sms
