### ISSUE TITLE
Documentation For Deeper Undestanding

### ISSUE THREAD

**Issue by FatihDurmus** [SigPloiter/SigPloit#138]
Hello, I hope you are fine. I need documentation for a deeper understanding. I'm looking for paid or free all solutions. I'm looking for documentation not just for ss7 also for understanding your project. Please inform me.
Best Regards.

**Comment by FatihDurmus** [comment]
fatihdurmus15[{@}]gmail[{dot}]com and thank you for response.

**Comment by Yakultie** [comment]
Hi, I am interested in more information/documentation too. Willing to offer decent pay in Bitcoin. Please contact me at my email which is listed on my GitHub profile. (bernard <atsign> bernent.co.uk)
