### ISSUE TITLE
[-]Error:SendRoutingInfo.jar Failed to launch

### ISSUE THREAD

**Issue by Josue198s** [SigPloiter/SigPloit#139]
MAP Dialog In okeTimeout for Dialog=1 and invokeId=0
[-]Error:SendRoutingInfo.jar Failed to launch

**Comment by SigPloiter** [comment]
please when using sigploit, either you will use it against a mobile network, or you are doing simulation for educational purpose then you need to have two VMs with sigploit one will run as the attacker and the other will run the server side jar file of the attack you are running

for example on another VM with the parameters provided use SendRoutingInfo.jar found under 'Testing/SS7/' directory
