### ISSUE TITLE
How to use the SS7 module

### ISSUE THREAD

**Issue by xiaoxie1979** [SigPloiter/SigPloit#143]
Hi @SigPloiter
Thank you for the code provided, I have installed it correctly，

Can you explain this in detail? Can you provide a detailed guide? thanks

"In order to attach the SS7 on real life target you should have an access to the SS7 network. It is often provided by VoIP providers, SMS providers, HLR lookup web application providers, you just need to dig deeper to find a suitable provider"

**Comment by SigPloiter** [comment]
Hello , thanks for installing the tool. As mentioned to Be able to work in
a real environment you need to get SS7 access. Other than that the server
side code provided could be used for simulation for education and hands on
