### ISSUE TITLE
SigPloit 

### ISSUE THREAD

**Issue by elitemacht** [SigPloiter/SigPloit#145]
Assalamu aleykum bro, really nice work for creating this tool. I hope you can make some new video tutorial because the last one was deleted from youtube. Can you contact me privatly please need some help yasinto-93@hotmail.com 

Thank you

**Comment by naveed-miya** [comment]
> Assalamu aleykum bro, really nice work for creating this tool. I hope you can make some new video tutorial because the last one was deleted from youtube. Can you contact me privatly please need some help [yasinto-93@hotmail.com](mailto:yasinto-93@hotmail.com)
> 
> Thank you

bro,i too need a video tutorial o this tool
unable to use it
