### ISSUE TITLE
live mode

### ISSUE THREAD

**Issue by C5LIFE** [SigPloiter/SigPloit#146]
hi i didnt know how to contact you directly. i was wondering if you could explain abit more on this
WIKI 3 how to use ss7
 'In order to attach the SS7 on real life target you should have an access to the SS7 network. It is often provided by VoIP providers, SMS providers, HLR lookup web application providers, you just need to dig deeper to find a suitable provider. "

i was wondering what is this esactly? would a hackrf one be suitable for this?
thanks

**Comment by C5LIFE** [comment]
could you contact me directly on c5life@topmail.com

**Comment by SigPloiter** [comment]
hi, no hackrf is used for another attack vector, which is the wireless
interface, this is more towards network side
