### ISSUE TITLE
Correct settings, but error in launch attack

### ISSUE THREAD

**Issue by 4m3k** [SigPloiter/SigPloit#147]
Hi @SigPloiter,
I've an error with your script. I'm testing it in "simulation mode". I've two VMs. One of this (client) has IP  "192.168.56.101", while the other one (server) has IP "192.168.56.102".
In the server I've launched "java -jar SendRoutingInfo.jar" of "Testing/Server/Attacks/Location_Tracking/SendRoutingInfo_Server" path.
On the client machine I've launched "python sigploit.py" .
I've selected "0) SendRoutingInfo" attack and I've set values via "set field value" command.
After that, I've received this error:
[-]MAP Dialog InvokeTimeout for Dialog=1 and invokeIk==
[-]Error:SendRoutingInfo.jar Failed to Launch

Where is the error? I've set properly all value and the two network card in the two machines.
Thank you

**Comment by SigPloiter** [comment]
please share the values you entered

**Comment by Eyong-Ebob** [comment]
please share your values with me. i have some issues,some values are missing in the given parameters like the global GT in location tracking( AnyTimeInterogation attack

**Comment by zeroplus4** [comment]
Can we talk on Telegram for quick conversations

Here is my id @Zeroplux4

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by klinton81** [comment]
Please someone to help me set the parameters

**Comment by zeroplus4** [comment]
chat me on telegram so i can assist you .....................< zeroplux4 >

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by klinton81** [comment]
What is your telegram number

**Comment by zeroplus4** [comment]
zeroplux4

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by attractor1** [comment]
I acquired this information for money as a lesson to use. I am ready to
share with you for a small compensation. if it suits you give me an answer.

Ср, 1 квіт. 2020, 22:30 користувач Eyong-Ebob <notifications@github.com>
пише:
