### ISSUE TITLE
Error when testing simulation mode

### ISSUE THREAD

**Issue by naymintun800** [SigPloiter/SigPloit#149]
I got this error when I testing the simulation mode .. I'm pretty sure I filled correctly the parameters as shown as on the Instruction..
MAP Dialog InvokeTimeout for Dialog=1 and invokeid=0
Error:SendRoutingInfo.jar Failed to Lunch,

**Comment by Eyong-Ebob** [comment]
please i wish to perform some test in sigploit framework in simulation mode but i dont know how to go about it even though i have installed it. i can not even see simulation mode on it.please help me, its for educational purpose. thanks

**Comment by zeroplus4** [comment]
What type of test are you to do

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Eyong-Ebob** [comment]
i wish to test the vulnerabilities with the server side code in sigploit framework to see the outcomes from the attacks in the simulation mode and get a view of what results can be obtained if does attacks were made in live mode. thanks

**Comment by Eyong-Ebob** [comment]
that is testing the vulnerabilities in SS7 in simulation mode, but i am finding it dificult setting the virtual lab and uploading the server side code for the test.

**Comment by zeroplus4** [comment]
For the test to be successful. You need to be on the sever side.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by SigPloiter** [comment]
Please refer to the wiki for instructions
