### ISSUE TITLE
Error in Live mod

### ISSUE THREAD

**Issue by naymintun800** [SigPloiter/SigPloit#150]
In Live mod .. I got this  . Can you help?
Is that cause because of I'm not using HackRF One?

[*]Set Client PC: 1
[*]Set Peer PC: 1
[*]Set Client IP: 103.200.134.148
[*]Set Client Port: 32790
[*]Set Peer IP: 198.204.237.10
[*]Set Peer Port: 80
[*]Set Network Indicator [0] International [2] National: 2
[*]Enter Target's MSISDN: [My PhoneNumber]
[*]Enter your MSC GT : [My PhoneNumber :)]
[*]Stack components are set...
[*]Initializing the Stack...
[*]Initializing SCTP Stack ....
log4j:WARN No appenders could be found for logger (org.mobicents.protocols.sctp.ManagementImpl).
log4j:WARN Please initialize the log4j system properly.
[+]Initialized SCTP Stack ....
[*]Initializing M3UA Stack ....
[+]Initialized M3UA Stack ....
[*]Initializing SCCP Stack ....
[+]Initialized SCCP Stack ....
[*]Initializing TCAP Stack ....
[+]Initialized TCAP Stack ....
[*]Initializing MAP Stack ....
[+]Initialized MAP Stack ....
[*]Locating Target: [My PhoneNumber :)]
[*]Location Retrieval for Target 959761350825 is processing..

[-]MAP Dialog InvokeTimeout for Dialog=1 and invokeId=0

**Comment by SigPloiter** [comment]
From where are these parameters you are getting this error because u don’t
have access and hackef is irrelevant to these types of attacks please read
more about SS7

**Comment by naymintun800** [comment]
Where can I read and more about ss7? Can you give me a good place or site?

**Comment by naymintun800** [comment]
Do I need Dialogic Tx series ss7 board?

**Comment by InnovaHacker** [comment]
for using sigploit in live mode, you have to get parameters from network provider like airtel, vodafone etc. if someone working in telcom company gives you these parameters for accessing ss7 network then you have to send an request & if telcom company accepts it then you can access ss7 Network.

**Comment by naymintun800** [comment]
I need the Global Title and Point Code from them .. I'm I right?

**Comment by byyuans345** [comment]
> Canlı modda.. Bunu anladım. Yardım edebilir misin?
> Bunun nedeni HackRF One kullanmamam mı?
> 
> [ _]İstemci PC'yi Ayarla: 1 [_ ]Eş PC'yi Ayarla: 1
> [ _]İstemci IP'sini Ayarla: 103.200.134.148 [_ ]İstemci Bağlantı Noktasını Ayarla: 32790
> [ _]Eş IP'yi Ayarla: 198.204.237.10 [_ ]Eş Bağlantı Noktasını Ayarla: 80
> [ _]Ağ Ayarla Gösterge [0] Uluslararası [2] Ulusal: 2 [_ ]Hedefin MSISDN'sini Girin: [Telefon Numaram]
> [ _]MSC GT'nizi girin: [Telefon Numaram :)] [_ ]Yığın bileşenleri ayarlandı...
> [ _]Yığın Başlatılıyor.. . [_ ] başlatılıyor SCTP Yığın ....
> log4j: kaydedicisi (org.mobicents.protocols.sctp.ManagementImpl) için bulunamadı hiçbir appenders WARN.
> log4j:WARN Lütfen log4j sistemini düzgün bir şekilde başlatın.
> [+]Başlatılan SCTP Yığını ....
> [ _]M3UA Yığını Başlatılıyor .... [+]Başlatılan M3UA Yığını .... [_ ]SCCP Yığını Başlatılıyor ....
> [+]Başlatılan SCCP Yığını ....
> [ _] TCAP Yığını Başlatılıyor .... [+]Başlatılan TCAP Yığını .... [_ ]MAP Yığını Başlatılıyor ....
> [+]Başlatılan MAP Yığını ....
> [ _]Hedef_ Konum _: [Telefon Numaram :)] __ [_ ]Konum Hedef 959761350825 için alma işleniyor..
> 
> [-]MAP İletişim Kutusu Dialog=1 ve invokeId=0 için InvokeTimeout

how to solve this problem help
