### ISSUE TITLE
Do I need to access E1 connection too?

### ISSUE THREAD

**Issue by kotunnyunt** [SigPloiter/SigPloit#152]
I know I have to ask to Mobile Network Providers to get the parameters and access to ss7 network.. But Dude! Do I need E1 connection to test the Sigploit live mode?

**Comment by SigPloiter** [comment]
No , it will be over IP

**Comment by SigPloiter** [comment]
its a physical connection same as ethernet but with lower throughput max of i guess 1.5Mbps
