### ISSUE TITLE
Simulation Issue

### ISSUE THREAD

**Issue by ICT-Researcher** [SigPloiter/SigPloit#153]
Hello @SigPloiter,
I wanted to run ATI or any other ss7 attack in simulation mode but it didn't work. Based on Readme file as the first step, values are set as below:
_(tracking)>show options

     Option                    	Value
     --------                 	------
     client_pc      		1
     server_pc      		2
     client_ip      		192.168.56.101
     client_port      		2905
     server_ip      		192.168.56.102
     server_port      		2906
     network_indicator      	0
     target_msisdn      	96599657765
     local_GT      		null_

Then following command for starting server side on same machine was used:
_virtual-machine:~/Downloads/SigPloit-master/Testing/Server/Attacks/Location_Tracking/AnyTimeInterrogation_Server$ sudo java -jar AnyTimeInterrogation.jar_

As you can see, after running ss7 ATI attack under siglpoit.py, the following error appeared :
_(tracking)>run
[*]Stack components are set...
[*]Initializing the Stack...
[*]Initializing SCTP Stack ....
log4j:WARN No appenders could be found for logger (org.mobicents.protocols.sctp.ManagementImpl).
log4j:WARN Please initialize the log4j system properly.
[+]Initialized SCTP Stack ....
[*]Initializing M3UA Stack ....
[+]Initialized M3UA Stack ....
[*]Initializing SCCP Stack ....
[-]Error initializing SCCP Stack: null_

The second problem is how I can see m3ua (signalling) links status between Sigloit machine and target operator in the real world?

Regards

**Comment by ICT-Researcher** [comment]
@SigPloiter, I used random local_GT (not mentioned related readme file) in  and sigloit goes to further steps as below, but still couldn't get proper result:

_(tracking)>set local_GT 123456789123456_
(tracking)>run
[*]Stack components are set...
[*]Initializing the Stack...
[*]Initializing SCTP Stack ....
log4j:WARN No appenders could be found for logger (org.mobicents.protocols.sctp.ManagementImpl).
log4j:WARN Please initialize the log4j system properly.
[+]Initialized SCTP Stack ....
[*]Initializing M3UA Stack ....
[+]Initialized M3UA Stack ....
[*]Initializing SCCP Stack ....
[+]Initialized SCCP Stack ....
[*]Initializing TCAP Stack ....
[+]Initialized TCAP Stack ....
[*]Initializing MAAP Stack ....
[+]Initialized MAP Stack ....
[*]Locating Target: 96599657765
[*]Location Retrieval for Target 96599657765 is processing..

[-]Error: MAP InvokeTimeout for Dialog=1 and invokeId=0_

**Comment by ICT-Researcher** [comment]
@SigPloiter as i mentioned in second comment GT issue is solved but, still not working(you can see the output in second comment). 
after setting GT value the error is:
_[-]Error: MAP InvokeTimeout for Dialog=1 and invokeId=0__

I use sigploiter simulation in same machine that i use siglpoit.py, is it ok? Or I should install another machine for attack simulation?

**Comment by SigPloiter** [comment]
Another machine ofcourse !!!

**Comment by mrbanker** [comment]
I have got the kali Linux os and I am also getting the same message. log4j:WARN No appenders could be found for logger. is this simply due to incorrect details inputted?

**Comment by mrbanker** [comment]
@SigPloiter

**Comment by SigPloiter** [comment]
its not an error, just logging warning

**Comment by mrbanker** [comment]
@SigPloiter are you selling telco access or know anyone that is? can you email me please mr_banker14@yahoo.com

**Comment by SigPloiter** [comment]
no

**Comment by SigPloiter** [comment]
Please here to post any issues or new ideas regarding the framework, not for such requests
