### ISSUE TITLE
Adding functionality

### ISSUE THREAD

**Issue by rextyler9030** [SigPloiter/SigPloit#157]
Hey, 
I am looking forward to add functionality of intercepting calls to this project. I know that it's done by spoofing the gsmSCF. If you don't mind providing me the source code of the java files , I would have an idea of you implemented MAP(mobile application part) in java.

**Comment by SigPloiter** [comment]
The idea of implementing call interception will not be of a big deal if you doing it all with pure SS7 its about decoding the voice traffic
