### ISSUE TITLE
Compilation terminated

### ISSUE THREAD

**Issue by finessin87** [SigPloiter/SigPloit#159]
When compiling from source, an error occurs (Failed building wheel for pysctp) setup resumes at installation of collected packages and then the process is terminated with a fatal error: netinet/sctp.h: No such file or directory #include <netinet/sctp.h>
                   ^
compilation terminated. Error: command ‘x86_64-linux-gnu-gcc’ failed with exit status 1. 
I’m running Kali Linux 18.4 GNOME Terminal 3.30.0

**Comment by SigPloiter** [comment]
make sure to install the package that supports sctp

sudo apt-get install libsctp-dev

**Comment by Travon112200** [comment]
I’m also getting this error
