### ISSUE TITLE
Having issues running any test.

### ISSUE THREAD

**Issue by DonDxDy** [SigPloiter/SigPloit#160]
Am am having issues when I run the test for AIT jar file as the below error which I believe is a hardcoded directory as MacOs does not allow to create directory in /home

java.io.FileNotFoundException: /home/gh0/restcomm-jss7-7.0.1383/ss7/maplog.log (No such file or directory)
TechMC-Air:home techservices$ mkdir -pv gh0
mkdir: gh0: Operation not supported

Also I won't mind if I get a step in running the ss7 or the ati 
my email is chigozirimogbogu@gmail.com

**Comment by SigPloiter** [comment]
Is that the server side jar file ? Because that’s not the attack I assume

**Comment by DonDxDy** [comment]
yes that is server side jar file. but if I could get guidance on steps to run the server side.

**Comment by SigPloiter** [comment]
sorry for my late reply, i shall fix it and send you guidance through your email later today

**Comment by bliw** [comment]
Hi. I seem to be having the same problem when trying to launch the test ATI jar. I've search the internet and I can't seem to find a proper way to test sigploit. I would be greatly thankful if you can send me the steps required to run the testing codes, as well as the proper method to modify jar executables to change the hard-coded values (ex IP, port etc.) in my email adress: bliwglane@gmail.com.

**Comment by dydfrancis** [comment]
Boss please i need guidelines on how to start i really need to pass this stage client pc
Port
On so on if you can provide a video tutorial on this sigploit that will be great thanks boss nwosuizuchukwu511@yahoo.com
