### ISSUE TITLE
error Initializing SCTP Host address cannot ne null

### ISSUE THREAD

**Issue by sahilc556** [SigPloiter/SigPloit#161]
![Uploading error Initializing SCTP Host address cannot ne null.jpeg…]()

**Comment by SigPloiter** [comment]
if you can resend the error please as the pic is not shoiwng

**Comment by zeroplus4** [comment]
Please how can this issue be resolved. 

Error: warn No appenders could be found  for logger(org.mobicents.protocols.stcp.managementimpl).

Error:initializing the sctp. Host address cannot be null.


ERROR:warn please initiate the log4j system properly. 

ERROR.:updatelocation.jar failed to launch. 



Here is the picture of the error massage.

**Comment by zeroplus4** [comment]
![20191130_194457](https://user-images.githubusercontent.com/50789110/69911889-4195c780-1422-11ea-857c-8daee775b562.jpg)

**Comment by zeroplus4** [comment]
Please how can this issue be resolved. 

Error: warn No appenders could be found  for logger(org.mobicents.protocols.stcp.managementimpl).

Error:initializing the sctp. Host address cannot be null.


ERROR:warn please initiate the log4j system properly. 

ERROR.:updatelocation.jar failed to launch. 



Here is the picture of the error massage.
