### ISSUE TITLE
Which external devices do i need ?

### ISSUE THREAD

**Issue by minanagehsalalma** [SigPloiter/SigPloit#171]
To perform a really test like the one that gets the accounts reset code !

**Comment by SigPloiter** [comment]
No hardware required

**Comment by minanagehsalalma** [comment]
Great ! Can we get a video of the tool performing this
https://youtu.be/tLVHdL9eOuI ?

**Comment by SigPloiter** [comment]
No hardware required but there are dependencies  to run it with

**Comment by minanagehsalalma** [comment]
in that YouTube video?

**Comment by SigPloiter** [comment]
No it’s not , please since there is no issues related to the code I will
have to close the issue , thanks

**Comment by minanagehsalalma** [comment]
Fine ... But what about a video where your tool performes that attack ?

**Comment by dydfrancis** [comment]
please i need this video tutorial

**Comment by dydfrancis** [comment]
i really need the video tutorial nwosuizuchukwu511@yahoo.com

**Comment by minanagehsalalma** [comment]
@dydfrancis  ask @SigPloiter  i don't know .....

And it's not a wise move from you sharing an email in comments you may get spammed a lot .
