### ISSUE TITLE
need help testing Sigploit.

### ISSUE THREAD

**Issue by bliw** [SigPloiter/SigPloit#173]
Hi. I seem to be having the same problem when trying to launch the test ATI jar. I've searched the internet and I can't seem to find a proper way to test sigploit. I would be greatly thankful if you can send me the steps required to run the testing codes, as well as the proper method to modify jar executables to change the hard-coded values (ex IP, port etc.) Here's my email address: bliwglane@gmail.com.

_Originally posted by @bliw in https://github.com/SigPloiter/SigPloit/issues/160#issuecomment-492982489_

**Comment by SigPloiter** [comment]
what is the error, thanks to send me an output of what happens

**Comment by SigPloiter** [comment]
the hardocded is only on the sever side, the source codes for server sides are provided if you want update them then compile

**Comment by pinoccio00** [comment]
does sigploit work on live ? i'm new here

**Comment by bliw** [comment]
Hi, Sorry for the late reply. I didn't want to create a new issue on
github, so im emailing you the issue description.

**Comment by bliw** [comment]
Sorry for the previous email.
