### ISSUE TITLE
Hard-Coded Paths outside of the build

### ISSUE THREAD

**Issue by dkillion** [SigPloiter/SigPloit#175]
When trying to run the UpdateLocation_Server to attempt offline static tests, I'm faced with this error messages:

```
:~/SigPloit-master/Testing/Server/Attacks/Interception/UpdateLocation_Server$ java -jar UpdateLocation.jar
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /home/gh0/restcomm-jss7-7.0.1383/ss7/maplog.log (No such file or directory)
...
0    [main] DEBUG UpdateLocationResp  - Initializing SCTP Stack ....
java.net.BindException: Cannot assign requested address
```

It seems the code has hard-coded calls to paths outside of the build environment.  I also don't see any easy configuration file to specify details for the server.

Are there any plans to improve the servers or clean up the references?

**Comment by SigPloiter** [comment]
The current issue is not in the path it will not terminate your issue is
that your probably supplying the wrong IP address

The server side will remain using hard coded servers it’s for simulation
after all

**Comment by dkillion** [comment]
This is what I'm talking about:

`/home/gh0/restcomm-jss7-7.0.1383/ss7/maplog.log (No such file or directory)`

This is a path hard-coded in the java jar that's...  your home dir.  I guess I could fix it, but I've no idea what the contents of this file are.  I can guess its a log, but short of downloading the restcomm-jss7 package that's all I can do with this.

If it's just a log file, then perhaps it would be cleaner to have the log either be defineable in a config file or command line, or just dump logs to the current directory instead of the hard-coded home directory.

Being able to specify the IP address this server listens on in a config file or command line parameter would be super-useful to add to these sample servers, instead of being hard-coded into the binary.

Being a "simulation" server doesn't mean it shouldn't have basic features like the ability to configure it for use.

**Comment by SigPloiter** [comment]
Ok will resolve it

**Comment by SigPloiter** [comment]
by the way the source code for the servers is available if you want to modify it

**Comment by pinoccio00** [comment]
does sigploit work on live ? i'm new here hello
