### ISSUE TITLE
UpdateLocation not working on real mode

### ISSUE THREAD

**Issue by brad7172** [SigPloiter/SigPloit#176]
Hey,

I get error {routing context :100} when testing UpdateLocation in real mode.
is there an issue on the core ?

Thx

**Comment by SigPloiter** [comment]
no its from sigploit, it shall be updated tonight
essentially routing context is provided as a parameter from your provider and should be the same in the request

**Comment by pinoccio00** [comment]
does sigploit work on live ? i'm new here @brad7172 @SigPloiter

**Comment by brad7172** [comment]
Some Map Ops. are fine but some others still need to be fixed.
It will be updated tonight @pinoccio00

**Comment by brad7172** [comment]
Any update @SigPloiter ?
P.S: I have found more issues on the stacks.

**Comment by SigPloiter** [comment]
if you find issues then post it to know it

**Comment by brad7172** [comment]
Lets update the code first to know if you have resolve them, only then i can re-test and see if it was related or not.
You told us that yesterday night you will make a new release, i don't see any update.

**Comment by SigPloiter** [comment]
this is not a blog, this is to open issues so if you have issues upload
logs that supports your claims, so fixing happens at once.

you will see the updates when they are ready

**Comment by SigPloiter** [comment]
its updated now
and if you have any issues it will be good to contribute and provide them otherwise they are just claims, so it will be good to contribute with issues or just wait till updated releases

**Comment by dydfrancis** [comment]
boss please i really need your help i want to hear from you dydfrancis10@gmail.com
