### ISSUE TITLE
There is not good help

### ISSUE THREAD

**Issue by reza01012003** [SigPloiter/SigPloit#178]
I am going to use your great code but I don't know how. I installed the code and chose the ss7 option. However, I don't know how to insert the phone number I want to hack. Could you please provide me with suitable documentation and maybe a better code? here is my email address: mrkaramoozravari@gmail.com

**Comment by SigPloiter** [comment]
please these is for educational purposes not for hacking and malicious
cases, so if you want to "hack" get familiar with the topic in details so
you can use it

**Comment by brad7172** [comment]
Hi @SigPloiter @reza01012003 

Depends on what the goal is. SS7 is a protocol family, not a single protocol. So it depends a lot. As we are speaking about a protocol totally outside the internet (eventhough it might often be tunneled over the internet these days), we are talking about a totally different beast. So unless you have an agreement with a telecom operator who has SS7, it will be pretty hard to get access. Secondly, you need some addresses (pointcodes, global titles) which you need to get from the regulatory or from some operator leasing it to you. And then it’s a question if they want to answer to you. Routing in the SS7 world is done statically (fully manually). This means all your target partners must know how to get back to you.

If you have solved that part, then you can communicate with other nodes and send them packets. Then it depends what that node is and what kind of firewall there is in place. Some operators have nothing and give you the key to the kingdom freely. Others don’t answer unless you are on their very restricted whitelist.

Also SigPloit is fully working on live mode so just forget about it for now.

Anyway @reza01012003  seeing your level and the way you want this you will not be able to succeed so just close this issue as it's not one and go learn about ss7

**Comment by reza01012003** [comment]
Thanks for your comments. I wanted to hack sb's whatsapp which is vitally important for me. I hoped you could help me. Is there any chance for me to do so?

**Comment by SigPloiter** [comment]
please this is not a hacking forum and Sigploit is not responsible on your
actions

**Comment by dydfrancis** [comment]
please boss make this tools user friendly i mean make us understand how it works i have try all i could this get this done but is not working out atlist i wanna spy my own number how will i do that please help dydfrancis10@gmail.com
