### ISSUE TITLE
SigPloit install requirements.txt failed

### ISSUE THREAD

**Issue by msfu101** [SigPloiter/SigPloit#180]
Hi there, i have a Problem with installing SigPloit requirements.txt.
the Output and error message is:

~/SigPloit# sudo pip2 install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: colorama>=0.3.9 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (0.4.1)
Requirement already satisfied: pyfiglet>=0.7.5 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (0.8.post1)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: configobj>=5.0.6 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (5.0.6)
Requirement already satisfied: IPy>=0.83 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5)) (0.83)
Collecting pysctp>=0.6 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/68/4f/8a11fd73939cb9a453aca3a11e88bc042656dc4b3865661da5121ba4bef0/pysctp-0.6.tar.gz
Building wheels for collected packages: pysctp
  Building wheel for pysctp (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Bg4ZzO/pysctp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Bg4ZzO/pysctp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-tRVIF_ --python-tag cp27
       cwd: /tmp/pip-install-Bg4ZzO/pysctp/
  Complete output (15 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying sctp.py -> build/lib.linux-x86_64-2.7
  running build_ext
  building '_sctp' extension
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Ra3Yar/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I/usr/include -I/usr/include/python2.7 -c _sctp.c -o build/temp.linux-x86_64-2.7/_sctp.o
  _sctp.c:11:10: fatal error: netinet/sctp.h: No such file or directory
   #include <netinet/sctp.h>
            ^~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pysctp
  Running setup.py clean for pysctp
Failed to build pysctp
Installing collected packages: pysctp
  Running setup.py install for pysctp ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Bg4ZzO/pysctp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Bg4ZzO/pysctp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-Tu4fKg/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-Bg4ZzO/pysctp/
    Complete output (15 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying sctp.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building '_sctp' extension
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Ra3Yar/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I/usr/include -I/usr/include/python2.7 -c _sctp.c -o build/temp.linux-x86_64-2.7/_sctp.o
    _sctp.c:11:10: fatal error: netinet/sctp.h: No such file or directory
     #include <netinet/sctp.h>
              ^~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Bg4ZzO/pysctp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Bg4ZzO/pysctp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-Tu4fKg/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

Can anybody tell me what i do wrong?
Thx in advance!

**Comment by MaySama** [comment]
Não necessariamente você precisa instalar, se sua máquina já tem python é só você executar " python sigploit.py "

**Comment by babiicakiis** [comment]
Try this command: sudo apt-get install libsctp-dev
Then try to run compilation again: sudo pip2 install -r requirements.txt
Let me know if that works for you

**Comment by msfu101** [comment]
Yes Man, that works!
Thank you
