### ISSUE TITLE
what are set values? how do i use it?

### ISSUE THREAD

**Issue by luckythandel** [SigPloiter/SigPloit#185]
like I know the set values - client_pc, serve_pc, client and server IP, port, MSISDN.
but I don't know what should I fill in it.
how would I get these values?
PLEASE HELP!!

**Comment by attractor1** [comment]
hi did you make out on your question?

**Comment by attractor1** [comment]
hi did you make out on your question?

**Comment by SigPloiter** [comment]
Please, i suggest to read a bit about SS7 you can look also in the wiki

**Comment by nickylimjj** [comment]
Refer to default values in the attack folder (most of them are stored in 

`<SigPloit dir>/Testing/Server/Attacks/Interception/UpdateLocation_Server/Parameters` or
`<SigPloit dir>/Testing/Server/Attacks/Interception/UpdateLocation_Server/README`)
