### ISSUE TITLE
How use and install with pip3 and python3

### ISSUE THREAD

**Issue by lvlafia** [SigPloiter/SigPloit#197]
Hi... Bro i try install requirements.txt with pip3 because i use python3 and pip3, but appears error, how i can use and install sigploit with pip3 and python3? thanks beforehand.

**Comment by attractor1** [comment]
Hi dude. write to mail
laniakeyakz@gmail.com

вт, 30 черв. 2020, 05:09 користувач lvlafia <notifications@github.com> пише:

**Comment by lvlafia** [comment]
I solved.
