### ISSUE TITLE
Error: Could not find or load main class AnyTimeInterrogation.jar

### ISSUE THREAD

**Issue by elbasha751** [SigPloiter/SigPloit#2]
i have problem after run script 
Error: Could not find or load main class AnyTimeInterrogation.jar

all requirement was installed and java  version is 
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by SigPloiter** [comment]
I am working on resolving this issue, i will update you once done

**Comment by SigPloiter** [comment]
issue should be fixed now, kindly clone it again and test it, to test it in a lab environment check the Tests folder that contains the server side code for each attack
