### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by nikolaytoplev** [SigPloiter/SigPloit#219]
I wanna build an app to get access to ss7 and intercept any number I want.
Could you possibly help me?

**Comment by SigPloiter** [comment]
this is for educational purpose and not responsible for any actions that
may seem malicious

**Comment by nikolaytoplev** [comment]
I have to complete this task for my graduation.
I think it is very easy for you.
Could you help me?

**Comment by SigPloiter** [comment]
Then I guess you can reach out to your university to get the SS7 access ,
but since this is just graduation why can you use the simulation mode only
?

**Comment by zeroplus4** [comment]
Chat me on whatsapp for quick conversation on
+12028885222

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by nikolaytoplev** [comment]
The task is to build in real mode.
Please help me.
Thank you.

**Comment by zeroplus4** [comment]
Chat me on whatsapp for assistance
+12028885222

Sent from ProtonMail mobile

-------- Original Message --------
