### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by TheTangledMind** [SigPloiter/SigPloit#220]
I had a lot of issues trying to install everything but eventually, I got everything installed. But when i try to run it I get the following.

(root💀kali)-[/opt/SigPloit-master]
└─# python3 sigploit.py                                                                                       1 ⨯
  File "/opt/SigPloit-master/sigploit.py", line 136
    print table[c][row],
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(table[c][row], end=" ")?

any suggestions on what is wrong or how to make it run?

**Comment by allenuwu** [comment]
yeah its the same problem for me

**Comment by Kalvelign** [comment]
use python 2

**Comment by kmac48** [comment]
I'm sorry I'm having the same issue- I don't understand how to go about using python 2. When I do try to get it it says it is mentioned, can't be found, but was replaced by python 3. I can get python 3 but not one or two. Any help would be greatly appreciated. Thank you

**Comment by zeroplus4** [comment]
Chat with me on whatsapp for quick conversation on how to get python2 working
+18102260003

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by TheTangledMind** [comment]
zeroplus4 would you be able to post those instructions here as I am also having the same issues still, also python 2 is depreciated now and soon to be removed I believe. What options will we have then?

One more question, What Linux distro was Sigploit built on & what distros currently are know to work?
I have tried it on kali and Tails. They both have issues but not the same issues so I wonder, as they are both task-specific distros am I just using an incompatible Linux distro? Should I be doing this on Arch or Ubuntu etc?

**Comment by TheTangledMind** [comment]
Ok I succeeded in a fully automatic install of the Requirements and successfully loaded SigPloit. Here is how.
* I am running Kali linux which I boot off a usb.
* I cloned my copy of Sigsploit which gives the directory a different name than the zip - may or maynot matter but Im trying to be thorough. 

* 1st issue that I had which started this thread was indeed fixed by installing python 2.
I am fairly certain that I  used apt-get to install it as per python.org instructions.
*also run this updated request from the sigsploit pull
     sudo apt-get install lksctp-tools libsctp1 libsctp-dev  

* After installing Python2.7 you need to check if you have pip2 install correctly. use the following commands: 
                                                                                                              
┌──(root💀kali)-[/home/kali/SigPloit]
└─# python --version
pip --version
Python 2.7.18
pip 20.3.4 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

// If you have something else go to python.org or pypi.org for instructions. 
// Note that manually installing pip for Python 2.7. requires you to find its specific installer.
* trying to run 
    pip2 install -r requirements.txt had several fails still. One fail was that I needed to install pip setuptools, while your at it make sure wheel is installed also
 
─(root💀kali)-[/home/kali/SigPloit]
└─# pip2 install wheel setuptools                                                                             2 ⨯
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.                                                                      
Requirement already satisfied: wheel in /usr/local/lib/python2.7/dist-packages (0.36.2)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (44.1.1)

Final error was resolved by correctly installing the headers for python, which I think are not there due to Kali linux not being a desktop OS. This is done via:

┌──(root💀kali)-[/home/kali/SigPloit]
└─# sudo apt-get install python-dev                                        
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
python-dev-is-python2 is already the newest version (2.7.18-9).
0 upgraded, 0 newly installed, 0 to remove and 439 not upgraded.
                                                                    
After that pip2 install -r req... etc worked perfectly.

Hope that helps
