### ISSUE TITLE
Access denied when "SiGploit.py" start

### ISSUE THREAD

**Issue by ElvinMT** [SigPloiter/SigPloit#6]
When I was running the installation process the last step do not allow me to run the "SiGploit.py".
What can I do?
Thanks!

**Comment by humptysharma123** [comment]
did you try the instruction in readme?
3) chmod +x installer.sh
4)./installer.sh
5) cd SigPloit/bin
6) ./SiGploit.py to start Sigploiting

**Comment by ElvinMT** [comment]
Yes, but in the last step, using the las command "./SiGploit.py to start Sigploiting" shows an denial message.

**Comment by humptysharma123** [comment]
what about 
` sudo su`
and then enter your password try running after.

**Comment by ElvinMT** [comment]
It dosent work

**Comment by humptysharma123** [comment]
how about you post the error message?

**Comment by ElvinMT** [comment]
Here is the error message:
bash: ./SiGploit.py: Permission denied

**Comment by ElvinMT** [comment]
Thaks I solved the problem using this:

chmod +x SiGploit.py

./SiGploit.py

**Comment by humptysharma123** [comment]
1. Check if you are root
2. chmod +x Sigploit.py
3. ./Sigploit.py
This should work if not try chmod u+x Sigploit.py

**Comment by SigPloiter** [comment]
thanks @humptysharma123 for your help and reply
