### ISSUE TITLE
Host Address Cannot be null

### ISSUE THREAD

**Issue by humptysharma123** [SigPloiter/SigPloit#7]
everytime i run the test and the actual ss7 stack i am getting this error

> root@kali:~/SigPloit/SS7/Tracking/PSI# java -jar ProvideSubscriberInfo.jar 
> *********************************************
> ***        Locating Target                ***
> *********************************************
> [*]Set Client PC: 127.0.0.1
> [-]Error: null
> [*]Initializing SCTP Stack ....
> log4j:WARN No appenders could be found for logger (org.mobicents.protocols.sctp.ManagementImpl).
> log4j:WARN Please initialize the log4j system properly.
> [-]Error initializing SCTP Stack: java.lang.Exception: Host address cannot be null
> [*]Initializing M3UA Stack ....
> [-]Error initializing M3UA Stack: java.lang.Exception: No Association found for name=clientAsscoiation
> [*]Initializing SCCP Stack ....
> [-]Error initializing SCCP Stack: java.lang.NullPointerException
> [*]Initializing TCAP Stack ....
> [+]Initialized TCAP Stack ....
> [*]Initializing MAAP Stack ....
> [+]Initialized MAP Stack ....
> [-]Error: No ASP found for given name ASP1
> 
> root@kali:~/SigPloit/SS7/Tracking/ATI# java -jar AnyTimeInterrogation.jar 
> *********************************************
> ***             Locating Target           ***
> *********************************************
> [*]Set Client PC: 127.0.0.1
> [-]Error: java.util.InputMismatchException
> [*]Initializing SCTP Stack ....
> log4j:WARN No appenders could be found for logger (org.mobicents.protocols.sctp.ManagementImpl).
> log4j:WARN Please initialize the log4j system properly.
> [-]Error initializing SCTP Stack: Host address cannot be null
> [*]Initializing M3UA Stack ....
> [-]Error initializing M3UA Stack: No Association found for name=clientAsscoiation
> [*]Initializing SCCP Stack ....
> [-]Error initializing SCCP Stack: null
> [*]Initializing TCAP Stack ....
> [+]Initialized TCAP Stack ....
> [*]Initializing MAAP Stack ....
> [+]Initialized MAP Stack ....
> [-]Error: No ASP found for given name ASP1

**Comment by SigPloiter** [comment]
Dear Friend, this should be ran against a server, to test it, please use the server side messages located under the "Testing" directory, in there you will find the values to use for each message.

Other than that you need SS7 access for real life scenarios
