### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by cn0xroot** [SigPloiter/SigPloit#9]
nice project!

can you tell me How to use it? is there any document\blog\wiki?

thanks!

**Comment by d3v1l401** [comment]
You compile it and parse needed parameters.

Of course, if you want to use it you need access to a VoIP network or if just testing a testing environment (emulated) should be more than enough.

**Comment by SigPloiter** [comment]
@d3v1l401 Thanks for your comment and reply, that is correct

@cn0xroot i will prepare the wiki and documenation that will have all the basic and essential info

**Comment by cn0xroot** [comment]
@d3v1l401  @SigPloiter  At frist,thanks for the quick reply.
@SigPloiter I look forward to your wiki and documenation

**Comment by SigPloiter** [comment]
@cn0xroot  i will do my best to finish it over the weekend

**Comment by SigPloiter** [comment]
@cn0xroot Wiki updated

**Comment by cn0xroot** [comment]
@SigPloiter cool!

**Comment by ayarifak** [comment]
@SigPloiter  i want attack server with ss7 vilnurabity but i dont have ip adress and  port how  can i cet it

**Comment by SigPloiter** [comment]
You need to find a SS7/ Sigtran provider to give you access and global
title and point code

**Comment by ayarifak** [comment]
i now but use all methode but i cant found
