### ISSUE TITLE
OS error

### ISSUE THREAD

**Issue by pirakill** [SigPloiter/SigPloit#97]
Message			Category
   --------                    --------
   0) SendRoutingInfo		 CAT1
   1) ProvideSubsriberInfo	 CAT2
   2) SendRoutingInfoForSM	 CAT3
   3) AnyTimeInterrogation	 CAT1

   or type back to go back to Attacks Menu
(LocationTracking)> 0
Traceback (most recent call last):
  File "./SiGploit.py", line 233, in <module>
    mainMenu()
  File "./SiGploit.py", line 210, in mainMenu
    attacksMenu()
  File "./SiGploit.py", line 139, in attacksMenu
    LocationTracking()
  File "./SiGploit.py", line 179, in LocationTracking
    tracking.sri()
  File "/root/Desktop/SigPloit/bin/tracking.py", line 22, in sri
    if jar_file not in os.listdir(sri_path):
OSError: [Errno 2] No such file or directory: '/root/SigPloit/SS7/Tracking/SRI'

**Comment by humptysharma123** [comment]
you should place the 'SigPloit' directory under the 'root' or 'home' directory so it should look like this '/root/SigPloit/' this should work.

**Comment by SigPloiter** [comment]
@humptysharma123 thanks that is correct

@pirakill sigploit should be cloned under the home directory, because the paths for the code is set as the below example

home_dir = os.path.expanduser('~')
sri_path = os.path.join(home_dir,'SigPloit/SS7/Tracking/SRI')

**Comment by pirakill** [comment]
thank you it works 👍
