### ISSUE TITLE
ApplicationContextName of non activated mapservice received IN SendRoutingInfoForSM

### ISSUE THREAD

**Issue by humptysharma123** [SigPloiter/SigPloit#99]
hey i have been receiving the above error while testing on local PC while sending SendRoutingInfoForSM but after searching i found the problem was on the server code 
`  private void initMAP()
    throws Exception
  {
    logger.debug("Initializing MAP Stack ....");
    
    this.mapStack = new MAPStackImpl("MAP-HLR", this.tcapStack.getProvider());
    this.mapProvider = this.mapStack.getMAPProvider();
    
    this.mapProvider.addMAPDialogListener(this);
    this.mapProvider.getMAPServiceSms().addMAPServiceListener(this);
    
    this.mapProvider.getMAPServiceSms().acivate();
    
    this.mapStack.start();
    logger.debug("Initialized MAP Stack ....");
  }`
you forgot to activate the mapStack so the fix would be by adding the below code
`this.mapProvider.getMAPServiceMobility().acivate();`

**Comment by SigPloiter** [comment]
thanks , i will update it right away

**Comment by SigPloiter** [comment]
@humptysharma123 SRISFOrSM uses mapdialog SMS and not the MAP service mobility, can you please share with me the exact error

**Comment by humptysharma123** [comment]
@SigPloiter sorry it was a rooki mistake i was playing with the server code making a call interception the error was in my code not yours but now i fixed it.

**Comment by SigPloiter** [comment]
Call interception will be released soon , it just has to many options and
other features I want to implement and include
